G_MODULE_EXPORT void on_button1_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button2_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button3_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button4_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button5_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button6_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button7_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button8_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button9_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button10_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button11_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button12_clicked(GtkButton*b);   
G_MODULE_EXPORT void on_button13_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button14_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button15_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button16_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button17_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button18_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button19_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button20_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button21_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button22_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button23_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button24_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button25_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button26_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button27_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button28_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button29_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button30_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button31_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button32_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button33_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button34_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button35_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button36_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button37_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button38_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button39_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button40_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button41_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button42_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button43_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button44_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button45_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button46_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button47_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button48_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button49_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button50_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button51_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button52_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button53_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button54_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button55_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button56_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button57_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button58_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button59_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button60_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button61_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button62_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button63_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button64_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button65_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button66_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button67_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button68_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button69_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button70_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button71_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button72_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button73_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button74_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button75_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button76_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button77_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button78_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button79_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button80_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button81_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button82_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button83_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button84_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button85_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button86_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button87_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button88_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button89_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button90_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button91_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button92_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button93_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button94_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button95_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button96_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button97_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button98_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button99_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button100_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button101_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button102_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button103_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button104_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button105_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button106_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button107_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button108_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button109_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button110_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button111_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button112_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button113_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button114_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button115_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button116_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button117_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button118_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button119_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button120_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button121_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button122_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button123_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button124_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button125_clicked(GtkButton*b);
G_MODULE_EXPORT void on_button126_clicked(GtkButton*b);

G_MODULE_EXPORT void on_entry1_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry2_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry3_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry4_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry5_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry6_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry7_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry8_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry9_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry10_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry11_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry12_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry13_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry14_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry15_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry16_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry17_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry18_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry19_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry20_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry21_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry22_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry23_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry24_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry25_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry26_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry27_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry28_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry29_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry30_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry31_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry32_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry33_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry34_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry35_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry36_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry37_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry38_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry39_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry40_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry41_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry42_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry43_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry44_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry45_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry46_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry47_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry48_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry49_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry50_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry51_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry52_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry53_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry54_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry55_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry56_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry57_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry58_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry59_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry60_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry61_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry62_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry63_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry64_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry65_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry66_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry67_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry68_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry69_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry70_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry71_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry72_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry73_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry74_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry75_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry76_changed(GtkEntry* e);
G_MODULE_EXPORT void on_entry77_changed(GtkEntry* e);

G_MODULE_EXPORT void on_comboentry1_changed(GtkEntry* e);
G_MODULE_EXPORT void on_comboentry2_changed(GtkEntry* e);
G_MODULE_EXPORT void on_comboentry3_changed(GtkEntry* e);

G_MODULE_EXPORT void on_checkbutton1_toggled(GtkCheckButton* b);
G_MODULE_EXPORT void on_checkbutton2_toggled(GtkCheckButton* b);
